In [9]:
import os
import numpy as np
import pandas as pd
from datetime import date
from sklearn.model_selection import KFold, train_test_split, StratifiedKFold, cross_val_score,GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import log_loss, roc_auc_score, auc, roc_curve
from sklearn.preprocessing import MinMaxScaler

In [4]:
DPath="./data/"
train_df= pd.read_csv(os.path.join(DPath,'train_offline.csv'))
test_df= pd.read_csv(os.path.join(DPath,'test_offline.csv'))

In [6]:
train_df.shape

(1160742, 7)

In [7]:
test_df.shape

(594142, 6)

In [10]:
def label(row):
    if np.isnan(row['Date_received']):
        return -1
    if not np.isnan(row['Date']):
        td = pd.to_datetime(row['Date'], format='%Y%m%d') -  pd.to_datetime(row['Date_received'], format='%Y%m%d')
        if td <= pd.Timedelta(15, 'D'):
            return 1
    return 0

train_df["label"] = train_df.apply(label, axis=1)
train_df["label"].value_counts()

 0    710665
-1    413773
 1     36304
Name: label, dtype: int64

In [13]:
train_df

,User_id,Merchant_id,Coupon_id,Discount_rate,Distance,Date_received,Date,label,weekday,weekday_type
0,1439408,2632,NaN,NaN,0.0,NaN,20160217.0,-1,NaN,0
1,1439408,2632,8591.0,20:1,0.0,20160217.0,NaN,0,3.0,0
2,1439408,2632,1078.0,20:1,0.0,20160319.0,NaN,0,6.0,0
3,1832624,3381,7610.0,200:20,0.0,20160429.0,NaN,0,5.0,0
4,2029232,3381,11951.0,200:20,1.0,20160129.0,NaN,0,5.0,0
5,2223968,3381,9776.0,10:5,2.0,20160129.0,NaN,0,5.0,0
6,73611,2099,12034.0,100:10,NaN,20160207.0,NaN,0,7.0,0
7,163606,1569,5054.0,200:30,10.0,20160421.0,NaN,0,4.0,0
8,3273056,4833,7802.0,200:20,10.0,20160130.0,NaN,0,6.0,0
9,94107,3381,7610.0,200:20,2.0,20160412.0,NaN,0,2.0,0
10,253750,8390,NaN,NaN,0.0,NaN,20160327.0,-1,NaN,0
11,253750,8390,7531.0,20:5,0.0,20160327.0,NaN,0,7.0,0
12,376492,1041,13490.0,30:5,2.0,20160127.0,NaN,0,3.0,0
13,1964720,7884,NaN,NaN,10.0,NaN,20160115.0,-1,NaN,0
14,1964720,7884,6704.0,20:1,10.0,20160215.0,NaN,0,1.0,0
15,1113008,1041,NaN,NaN,2.0,NaN,20160114.0,-1,NaN,0
16,1113008,1041,11197.0,30:5,2.0,20160114.0,NaN,0,4.0,0
17,2881376,5341,111.0,30:5,1.0,20160207.0,NaN,0,7.0,0
18,2881376,8390,7531.0,20:5,0.0,20160321.0,20160329.0,1,1.0,0
19,2881376,5341,111.0,30:5,1.0,20160207.0,NaN,0,7.0,0
20,2881376,8390,NaN,NaN,0.0,NaN,20160321.0,-1,NaN,0
21,4061024,2709,2840.0,100:10,10.0,20160129.0,NaN,0,5.0,0
22,4061024,3381,7610.0,200:20,10.0,20160426.0,NaN,0,2.0,0
23,4061024,7555,9871.0,30:5,10.0,20160409.0,NaN,0,6.0,0
24,4061024,3381,9776.0,10:5,10.0,20160129.0,NaN,0,5.0,0
25,7073472,2934,NaN,NaN,0.0,NaN,20160322.0,-1,NaN,0
26,7073472,3381,7610.0,200:20,0.0,20160326.0,NaN,0,6.0,0
27,7073472,2934,5686.0,30:5,0.0,20160322.0,NaN,0,2.0,0
28,7073472,6485,9407.0,100:10,0.0,20160130.0,NaN,0,6.0,0
29,7073472,2934,5686.0,30:5,0.0,20160322.0,NaN,0,2.0,0
...,...,...,...,...,...,...,...,...,...,...
1160712,3400544,3485,NaN,NaN,0.0,NaN,20160414.0,-1,NaN,0
1160713,3400544,6454,14031.0,100:10,2.0,20160131.0,NaN,0,7.0,0
1160714,3400544,3485,NaN,NaN,0.0,NaN,20160115.0,-1,NaN,0
1160715,457900,7907,13118.0,150:30,NaN,20160418.0,NaN,0,1.0,0
1160716,2876768,6901,NaN,NaN,0.0,NaN,20160421.0,-1,NaN,0
1160717,179830,3381,1807.0,300:30,0.0,20160124.0,NaN,0,7.0,0
1160718,179830,4059,7166.0,100:10,7.0,20160124.0,NaN,0,7.0,0
1160719,179830,6434,10050.0,50:5,1.0,20160123.0,NaN,0,6.0,0
1160720,179830,6284,4567.0,50:10,1.0,20160124.0,NaN,0,7.0,0
1160721,179830,6284,7379.0,50:10,1.0,20160124.0,NaN,0,7.0,0
1160722,179830,3710,13056.0,150:10,4.0,20160124.0,NaN,0,7.0,0
1160723,179830,2099,12034.0,100:10,1.0,20160124.0,NaN,0,7.0,0
1160724,179830,4660,1480.0,100:10,0.0,20160125.0,NaN,0,1.0,0
1160725,179830,5341,7751.0,50:10,0.0,20160123.0,NaN,0,6.0,0
1160726,179830,7555,17.0,30:5,7.0,20160123.0,NaN,0,6.0,0
1160727,179830,760,3237.0,20:5,0.0,20160124.0,NaN,0,7.0,0
1160728,179830,2099,12034.0,100:10,1.0,20160203.0,NaN,0,3.0,0
1160729,343276,4206,NaN,NaN,5.0,NaN,20160425.0,-1,NaN,0
1160730,653784,195,NaN,NaN,0.0,NaN,20160418.0,-1,NaN,0
1160731,653784,195,NaN,NaN,0.0,NaN,20160416.0,-1,NaN,0
1160732,3795296,5341,111.0,30:5,0.0,20160129.0,NaN,0,5.0,0
1160733,188086,6568,NaN,NaN,0.0,NaN,20160415.0,-1,NaN,0
1160734,188086,6568,4723.0,30:1,0.0,20160415.0,NaN,0,5.0,0
1160735,188086,6568,NaN,NaN,0.0,NaN,20160417.0,-1,NaN,0
1160736,212662,3532,NaN,NaN,1.0,NaN,20160308.0,-1,NaN,0
1160737,212662,2934,5686.0,30:5,2.0,20160321.0,20160330.0,1,1.0,0
1160738,212662,3532,5267.0,30:5,1.0,20160322.0,NaN,0,2.0,0
1160739,212662,2934,5686.0,30:5,2.0,20160321.0,20160322.0,1,1.0,0
1160740,212662,3532,NaN,NaN,1.0,NaN,20160322.0,-1,NaN,0
1160741,212662,2934,NaN,NaN,2.0,NaN,20160321.0,-1,NaN,0

In [14]:
# Generate features - weekday acquired coupon
def getWeekday(row):
    if (np.isnan(row)) or (row==-1):
        return row
    else:
        return pd.to_datetime(row, format = "%Y%m%d").dayofweek+1 # add one to make it from 0~6 -> 1~7

train_df['weekday'] = train_df['Date_received'].apply(getWeekday)
test_df['weekday'] = test_df['Date_received'].apply(getWeekday)

# weekday_type (weekend = 1)
#if the day of the week is not a weekend, the value will be 0.  
train_df['weekday_type'] = train_df['weekday'].astype('str').apply(lambda x : 1 if x in [6,7] else 0 ) # apply to trainset
test_df['weekday_type'] = test_df['weekday'].astype('str').apply(lambda x : 1 if x in [6,7] else 0 ) # apply to testset

In [15]:
weekdaycols = ['weekday_' + str(i) for i in range(1,8)]
print(weekdaycols)

tmpdf = pd.get_dummies(train_df['weekday'].replace(-1, np.nan))
tmpdf.columns = weekdaycols
train_df[weekdaycols] = tmpdf

tmpdf = pd.get_dummies(test_df['weekday'].replace(-1, np.nan))
tmpdf.columns = weekdaycols
test_df[weekdaycols] = tmpdf

['weekday_1', 'weekday_2', 'weekday_3', 'weekday_4', 'weekday_5', 'weekday_6', 'weekday_7']

In [17]:
# Generate features - coupon discount and distance
def getDiscountType(row):
    if row == 'null':
        return 'null'
    elif ':' in row:
        return 1
    else:
        return 0

def convertRate(row):
    """Convert discount to rate"""
    if row == 'null':
        return 1.0
    elif ':' in row:
        rows = row.split(':')
        return 1.0 - float(rows[1])/float(rows[0])
    else:
        return float(row)
def getDiscountMan(row):
    if ':' in row:
        rows = row.split(':')
        return int(rows[0])
    else:
        return 0

def getDiscountJian(row):
    if ':' in row:
        rows = row.split(':')
        return int(rows[1])
    else:
        return 0

def processData(df):
    
    # convert discunt_rate
    df['discount_rate'] = df['Discount_rate'].astype('str').apply(convertRate)
    df['discount_man'] = df['Discount_rate'].astype('str').apply(getDiscountMan)
    df['discount_jian'] = df['Discount_rate'].astype('str').apply(getDiscountJian)
    df['discount_type'] = df['Discount_rate'].astype('str').apply(getDiscountType)
    # convert distance
    df.loc[df.Distance.isna(), "Distance"] = 99
    return df

train_df = processData(train_df)
test_df = processData(test_df)

In [27]:
train.to_csv("train.csv", index=False)
valid.to_csv("valid.csv", index=False)
#test_df.to_csv("test_df_processing.csv", index=False)

In [19]:
## Naive model
def split_train_valid(row, date_cut="20160416"):
    is_train = True if pd.to_datetime(row, format="%Y%m%d") < pd.to_datetime(date_cut, format="%Y%m%d") else False
    return is_train
    
df = train_df[train_df['label'] != -1].copy()
df["is_train"] = df["Date_received"].apply(split_train_valid)
train = df[df["is_train"]]
valid = df[~df["is_train"]]
train.reset_index(drop=True, inplace=True)
valid.reset_index(drop=True, inplace=True)
print("Train size: {}, #positive: {}".format(len(train), train["label"].sum()))
print("Valid size: {}, #positive: {}".format(len(valid), valid["label"].sum()))

Train size: 667753, #positive: 32472
Valid size: 79216, #positive: 3832

In [20]:
original_feature = ['discount_rate',
                    'discount_type',
                    'discount_man', 
                    'discount_jian',
                    'Distance', 
                    'weekday', 
                    'weekday_type'] + weekdaycols
print(len(original_feature),original_feature)

14 ['discount_rate', 'discount_type', 'discount_man', 'discount_jian', 'Distance', 'weekday', 'weekday_type', 'weekday_1', 'weekday_2', 'weekday_3', 'weekday_4', 'weekday_5', 'weekday_6', 'weekday_7']

In [ ]:
predictors = original_feature
print(predictors)

def check_model(data, predictors):
    
    classifier = lambda: SGDClassifier(
        loss='log', 
        penalty='elasticnet', 
        fit_intercept=True, 
        max_iter=100, 
        shuffle=True, 
        n_jobs=1,
        class_weight=None)

    model = Pipeline(steps=[
        ('ss', StandardScaler()),
        ('en', classifier())
    ])

    parameters = {
        'en__alpha': [ 0.001, 0.01, 0.1],
        'en__l1_ratio': [ 0.001, 0.01, 0.1]
    }

    folder = StratifiedKFold(n_splits=3, shuffle=True)
    
    grid_search = GridSearchCV(
        model, 
        parameters, 
        cv=folder, 
        n_jobs=-1, 
        verbose=1)
    grid_search = grid_search.fit(data[predictors], 
                                  data['label'])
    
    return grid_search

In [ ]:
model = check_model(train, predictors)

In [ ]:
y_valid_pred = model.predict_proba(valid[predictors])
valid1 = valid.copy()
valid1['pred_prob'] = y_valid_pred[:, 1]

In [ ]:
from sklearn.metrics import roc_auc_score, accuracy_score
auc_score = roc_auc_score(y_true=valid.label, y_score=y_valid_pred[:,1])
acc = accuracy_score(y_true=valid.label, y_pred=y_valid_pred.argmax(axis=1))
print("Validation AUC: {:.3f}, Accuracy: {:.3f}".format(auc_score, acc))

In [ ]:
targetset = dftest.copy()
print(targetset.shape)
targetset = targetset[~targetset.Coupon_id.isna()]
targetset.reset_index(drop=True, inplace=True)
testset = targetset[predictors].copy()

y_test_pred = model.predict_proba(testset[predictors])
test1 = testset.copy()
test1['pred_prob'] = y_test_pred[:, 1]
print(test1.shape)

In [ ]:
output = pd.concat((targetset[["User_id", "Coupon_id", "Date_received"]], test1["pred_prob"]), axis=1)
print(output.shape)

output.loc[:, "User_id"] = output["User_id"].apply(lambda x:str(int(x)))
output.loc[:, "Coupon_id"] = output["Coupon_id"].apply(lambda x:str(int(x)))
output.loc[:, "Date_received"] = output["Date_received"].apply(lambda x:str(int(x)))
output["uid"] = output[["User_id", "Coupon_id", "Date_received"]].apply(lambda x: '_'.join(x.values), axis=1)
output.reset_index(drop=True, inplace=True)

In [ ]:
### NOTE: YOUR SUBMITION FILE SHOULD HAVE COLUMN NAME: uid, label
out = output.groupby("uid", as_index=False).mean()
out = out[["uid", "pred_prob"]]
out.columns = ["uid", "label"]
# out.to_csv("baseline_example.csv", header=["uid", "label"], index=False) # submission format
out.head()